import { useEffect } from 'react'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'

import { IWork } from './api/works'

import { useWorks } from 'hooks/works'

import { api } from 'services/api'

import { Layout } from 'components/Layout'
import { FilterList } from 'components/FilterList'
import { GridList } from 'components/GridList'

interface IHome {
  works: IWork[]
}

const Home: NextPage<IHome> = ({ works }) => {
  const {
    search,
    filterWorks,
    handleSearch,
    handleRemoveSearchLang,
    handleRemoveAll,
    handleSetWorks,
  } = useWorks()

  useEffect(() => {
    handleSetWorks(works)
  }, [])

  const handleLanguage = (lang: string) => {
    handleSearch(lang)
  }

  const handleRemoveLanguage = (lang: string) => {
    handleRemoveSearchLang(lang)
  }

  const handleRemoveLanguageAll = () => {
    handleRemoveAll()
  }

  return (
    <>
      <Head>
        <title>Template Works</title>
        <meta name="description" content="Generated by template works" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {search.length > 0 && (
          <FilterList
            data={search}
            handleRemove={handleRemoveLanguage}
            handleRemoveAll={handleRemoveLanguageAll}
          />
        )}
        <GridList
          works={filterWorks.length > 0 ? filterWorks : works}
          search={search}
          handleLanguage={handleLanguage}
        />
      </Layout>
    </>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const response = await api.get('works')

  return {
    props: {
      works: response.data,
    },
  }
}
